### ISSUE TITLE
Finally build a GUI

### ISSUE THREAD

**Issue by livioso** [livioso/turbo-octo-hipster#8]

**Comment by mariuskueng** [comment]
Checkout http://shoesrb.com
It's a modern framework for building desktop apps in ruby. It also comes with an .app wrapper.

I know that a native app (cocoa) would be really nice. But because all scripts are in ruby I think we should stick to the same language. And speaking of the future we maybe could cover a system independent solution.

I think we could give this a try!

![](http://shoesrb.com/img/wt/003.png)
![](http://shoesrb.com/img/wt/011.png)
![](http://shoesrb.com/img/wt/012.png)

**Comment by livioso** [comment]
Looks interesting to me but I'm not convinced yet. Is it just me or does it look "ugly"? 
I mean of course better than nothing but the question remains: Wouldn't we be better off with a AppleScript-ish approach? I don't know but it doesn't convinced me because it lacks quite a few native OSX features, doesn't it? 

Cheers, Livio :)
